name: run python code

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 5 * * *'
    - cron: '30 8 * * *'

jobs:
  run-code:
    runs-on: ubuntu-latest
    
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      MATTERMOST_WEBHOOK_HEADER: ${{secrets.MATTERMOST_WEBHOOK_HEADER}}
      MATTERMOST_WEBHOOK: ${{secrets.MATTERMOST_WEBHOOK}}
      NOTION_BLOCK_ID: ${{secrets.NOTION_BLOCK_ID}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./notion-alarm

      - name: Run Python script
        run: python app.py
        working-directory: ./notion-alarm
